.TH ACCOUNT 1
.SH NAME
account \- creates log-ins and deletes an account
.SH SYPNOSIS
\fBaccount\fP --create | --login | --remove username password
\fBaccount\fP [--help] 
.SH DESCRIPTION
\fBaccount\fP manages the accounts that will be used by the
man programs of this repository
.SH OPTIONS
.TP
\fB--create\fP
creates an account, requires two arguments, username and password string
.TP
\fB--login\fP
access an account, requires two arguemnts, username and password string
.TP
\fB--remove\fP
removes an account, requires two arguements, username and password string
.TP
\fB--help\fP
shows all available commands, requires no arguemnts
.SH FILES
.TP
/users/, /users/accounts.txt
the users directory and files
.SH "SEE ALSO"
handler(1), cbook(1)
.SH BUGS
when account is registered and the program is killed halfway 
it cannot be deleted/ logged-in