.TH commline 1
.SH NAME
\fBcommline \fP\-handles the communication between two users
.SH SYNOPSIS
.TP
\fBcommline \fP [--access | --delete | --alter | --delete | --add] \fI[account_name]\fP
.TP
\fBcommline\fP [--help | --view]
.SH DESCRIPTION
\fBcommline \fP\-handles the communication between two users by 
the means of permisions, and account entries
.SH OPTIONS
.TP
\fB--add\fP
add an account entry to the user he can acces, do note that it must
be granted permision by the other user to be accessible,  requires one
argument: account name string
.TP
\fB--delete\fP
removes an account entry to the user he can acces, 
requires one argument: account name string
.TP
\fB--view\fP
view all the entries that a user have
.TP
\fB--alter\fP
grant or revoke a permision that a user has to your account, 
requires one argument: account name string
.TP
\fB--help\fP
prints all the possible commands to the console
.SH FILES
.TP
/users/user/commline.txt
stores all the lines of communication the user has
.SH "SEE ALSO"
handler(1), cbook(1), accounts(1), chat(1), todolist(1)
.SH BUGS
no known bugs as of now